TRON-US/go-btfs

- Dockerfile
- bin/container_daemon
- Add `patch` dependency in dockerfile build
- Fix daemon start script binary -> btfs
- Change perms on bin directory in dockerized daemon
> fix: docker build issues

- core/corehttp/proxy.go
- mk/golang.mk
Also fix the index out of range caused panic
> Remove builder's specific path from panic

- test/sharness/Rules.mk
- test/sharness/lib/test-lib.sh
- test/sharness/t0010-basic-commands.sh
initial commit to getting the tests found in the test/sharness to run properly.
> BTFSINFRA-328 fix sharness test basic-commands

- test/sharness/lib/test-lib-hashes.sh
- test/sharness/lib/test-lib.sh
- test/sharness/t0020-init.sh
fix sharness test helpers that start and stop the daemon and also get the init tests to pass.
> BTFSINFRA-332 fix sharness helpers and init test

- analytics/analytics.go
Simple fix that does the job. But...
PLEASE PLEASE PLEASE could you test it yourself multiple times? I was able to replicate the panic only once before the fix.
> Added error checking while polling CPU Info.

- package.sh
change md5 command to be more common one -  that's available for both…
> change of md5 command

- namesys/dns_test.go
- namesys/ipns_resolver_validation_test.go
- namesys/namesys_test.go
- namesys/republisher/repub_test.go
- namesys/resolve/pathresolver_test.go
- namesys/resolve_test.go
$ go test
PASS
ok  	github.com/TRON-US/go-btfs/namesys	0.207s
> Fix namesys unit test

- core/corehttp/gateway_test.go
make test passed:
ok  	github.com/TRON-US/go-btfs/core/corehttp	(cached)
> Fix unit test gateway_test.go

- cmd/btfs/init.go
This PR introduces seed generation using BIP39 and key pair generation using BIP32. In addition to that, it allows for a seed phrase import, which similarly to private key import permits the user to transfer their account across multiple machines.
> Seed generation with BIP39

- go.mod
Simple fix to the go-btfs-config release tag.
> Fixed the go-btfs-config version.

- cmd/btfs/generatekey_test.go
- cmd/btfs/init.go
- go.mod
- go.sum
added unit for seed phrase related key import
> [BTFSINFRA-436] Unit test

- autoupdate/main.go
retry the start up test twice and return error code if fails.
> [BTFSINFRA-467] return error code on startup test failure

- go.mod
- go.sum
> Re-fix go 1.13 build after the temp fix repo force-pushed the earlier

- cmd/btfs/autoupdate.go
we need to make the autoupdate.go smarter so it can deal with using the CDN dist.btfs.io files which are compressed or the raw.githubusercontent.com/TRON-US/btfs-binary-releases/master which are not compressed.
> BTFSINFRA-487 add struct to contain info update url and un/compressed

- cmd/btfs/daemon.go
added a time out for get test 
change log to fmt.printf since those are critical information
tested by turning off laptop's wifi and get file did time out.
> [BTFSINFRA-500] add time out to get test.

- version.go
> BTFSINFRA-520 up version number and change uri in api path

- patches/go-libp2p-kad-dht-dht_net.go.patch
- patching.sh
> [BTFSINFRA-504] patch memory leak

- cmd/btfs/daemon.go
- cmd/btfs/functest.go
kill the sub process rather than the main process
> [BTFSINFRA-521] new timeout mechanism

- Dockerfile.unit_testing
- bin/test-go-mod
- mk/golang.mk
add a new script to run "go mod tidy" and then check for diffs.  return exit code 1 (fail) if diffs are found and added to test_go_mod make option.  also added this to the make test_short option.
> BTFSINFRA-533 add make test_go_mod option

- cmd/btfs/daemon.go
- cmd/btfs/functest.go
Also update the btfs add test file content to btfs peerId and timestamp
> [BTFSINFRA-525] Update btfs add test file content to btfs peerId and timestamp

- version.go
up the rev version. will need release notes @tycm4109.
> release_0.2.1 update version file

- core/commands/storage.go
Notice, the work flow can take longer because it need to find peer in network.
> Btfs 793 swarm connect

- core/coreapi/unixfs.go
- go.sum
refactoring
return a specific struct
return []byte
no
none
return []byte rather than EciesMetadata instance
> refactoring return values

- .github/PULL_REQUEST_TEMPLATE.md
- .github/example_pull_request.md
PR template update
Old template has checklist on top
New template has checklist at bottom (making actual changes more visible)
No
N/A
New template has checklist at bottom (making actual changes more visible) 
---
* **Please make sure the …
> Move checklist reqs to bottom of PR template to make changes more visible

- core/commands/id.go
feature
https://tronnetwork.atlassian.net/browse/BTFS-947
no
none
return DaemonProcessId when btfs id is called
---
> [BTFS-947]feat: `btfs id` return DaemonProcessID

- go.mod
- go.sum
Dep fix
Windows build is broken
Windows build is happy again
Tested locally with `GOOS=windows GOARCH=amd64 make build`
No
- Update golang.org/x/sys to latest to fix windows build
---
* **Please make sure the following procedures have been …
> Update golang.org/x/sys to latest to fix windows build

- core/commands/id.go
feature
none
`btfs id` return daemon process id
no
none
`btfs id` return daemon process id
---
> return daemon process id

- go.mod
- go.sum
- spin/analytics.go
Refactoring
send node metrics with http client.
send node metrics with grpc client.
nope
https://github.com/TRON-US/go-btfs-common/pull/15
http client -> grpc client
---
* **Please make sure the following procedures have been applied before …
> [BTFS-928]switch status client from http to grpc

- analytics/analytics.go
- go.mod
- go.sum
Refactoring
send node metrics with http client.
send node metrics with grpc client.
nope
https://github.com/TRON-US/go-btfs-common/pull/15
http client -> grpc client
---
* **Please make sure the following procedures have been applied before …
> [BTFS-928]for v0.2.3 release: switch to grpc client

- core/coreapi/unixfs.go
- core/coreapi/unixfs_test.go
- go.mod
feature
can pass a private key file path for decryption
can pass a private key file path for decryption
---
> [BTFS-951]feat: read private key from specified file path.

- cmd/btfs/daemon.go
- core/commands/storage.go
- core/hub/sync.go
- go.mod
- go.sum
- spin/analytics.go
Update services url
Only reads status serve domain from config
Now reads more services from config (status, hub, escrow, guard)
Not really, but in order to use hub hosts sync, you need to update config now.
https://github.com/TRON-US/go-btfs-config/pull/15
- Update status server domain config …
> Update services config

- cmd/btfs/daemon.go
trivial -- code standardized
---
> [BTFS-1121] trivial tweaks -- standardize

- core/coreapi/unixfs.go
- core/coreunix/add.go
- core/coreunix/test/metadata_test.go
- go.mod
- go.sum
BTFS-1027: Metadata on directory object should work.
"btfs add -m $metadata-string $directory" on directory does not attach metadata under the given directory.
"btfs add -m $metadata-string $directory" attach metadata as child under the given directory.
N/A
https://github.com/TRON-US/go-unixfs/pull/17 …
> BTFSBTT-1027: metadata on directory object should work

- core/commands/commands_test.go
- core/commands/guard.go
- core/commands/root.go
- core/commands/storage.go
- core/commands/storage/challenge_test.go
- core/commands/storage/hosts.go
- core/commands/storage/hosts_test.go
- core/commands/storage/reed_solomon.go
- core/commands/storage/reed_solomon_test.go
- core/coreunix/test/add.go
- core/escrow/escrow.go
- core/guard/challenge.go
- core/guard/conn.go
- go.mod
- go.sum
- spin/analytics.go
- spin/hosts.go
Feature: send challenge questions from renter to guard
Does not send to guard yet, and no way to test
Helpers to send to guard + test command integration
No
https://github.com/TRON-US/go-btfs/pull/251 should be reviewed first
- Add send questions to guard helpers under core/guard/challenge.go and …
> BTFS-1004: Prep guard challenges (part 2) 

- core/commands/storage.go
- core/commands/storage/challenge.go
- core/commands/storage/challenge_test.go
- core/commands/storage/session.go
- core/guard/challenge.go
in addition to a single shard DAG.
Feature
Host challenges include only questions about a shard
Host challenges include questions on a shard + root + meta DAGs
- Challenges generate questions from shard DAG + root DAG (node only) + metadata DAG
---
* **Please check if the PR fulfills these …
> BTFS-1098: Adjust challenge to take questions from root + meta DAG nodes

- core/commands/storage.go
- core/escrow/escrow.go
- go.mod
- go.sum
> Btfs 1033 payin

- core/corehttp/webui.go
webui update
- Update to release webui version https://github.com/TRON-US/go-btfs/blob/release/core/corehttp/webui.go
---
> Update to v0.2.3 release webui

- cmd/btfs/daemon.go
- core/commands/storage.go
- spin/settings.go
> BTFS-698 refactor

- analytics/analytics.go
- go.mod
- go.sum
Bug fix.
not sending h_val
send h_val
no
https://github.com/TRON-US/go-btfs-common/pull/48
---
> [BTFS-1197]: Release fix hval

- core/commands/storage.go
bug fix
int overflows
fix the overflows
---
> fix int overflows

- core/commands/storage.go
- core/escrow/escrow.go
- core/guard/conn.go
- spin/analytics.go
> refactor to pass context rather than context.Background()

- autoupdate/main.go
- cmd/btfs/autoupdate.go
- cmd/btfs/daemon.go
- core/escrow/escrow.go
- go.mod
- go.sum
- spin/analytics.go
bug fix from v0.2.4 release
- send hval from analytics
- pass hval to new daemon during auto update process
---
> Fixes from v0.2.4 -> master

- version.go
string change to up the version
> BTFS-1205 up version 0.2.4

- core/commands/storage.go
Feature
Host adds a file but does not pin
Host pins any stored file
- Defaultly pin on host stored files
---
> BTFS-646: Pin on host stored files

- core/commands/guard.go
- core/commands/storage.go
- core/guard/challenge.go
- core/guard/conn.go
- core/guard/contract.go
feature
- Re-factor guard helpers in storage.go and core/guard/contract.go
- After uploading file meta, send challenge questions.
- Re-factor so `btfs guard test send-challenges` share some helpers with the renter payment flow logic of sending questions.
---
* **Please check if the PR fulfills these …
> BTFS-1170: Renter sends challenge questions to guard

- core/commands/storage/hosts.go
bug fix
the hosts is serded by different ways
uniform to proto serde
np
np
---
> change json serde to proto serde

- go.mod
- go.sum
- spin/analytics.go
> refactor: merge DataCollection and protobuf Node in spin/analytics

- core/commands/storage.go
- core/commands/storage/challenge.go
- core/commands/storage/challenge_test.go
- core/commands/storage/session.go
bugfix
host only stores shard
host stores root + meta + one shard
---
> BTFS-1097: Host persists root + metadata dags in addition to shard

- core/commands/guard.go
- core/commands/storage.go
- core/escrow/escrow.go
> BTFS-1267: Adjust default params to int so both http and cli work

- core/commands/storage/hosts.go
> remove fmt print

- go.mod
- go.sum
bug fix
BTFS-1266
BTFS-1266
---
> upgrade go-btfs-chunker to v0.2.7

- core/commands/storage.go
- core/escrow/escrow.go
feature
https://tronnetwork.atlassian.net/browse/BTFS-1169
check escrow payment for a contract
No
No
Payment work flow query escrow GRPCc interface to see if a contract has been paid in.
---
- [*] The subject of this PR contains a JIRA ticket …
> Add check escrow isPaid function

- core/commands/storage.go
- core/commands/storage/session.go
> Refactor session and persist contract on Renter

- core/commands/storage.go
Refactor session and persist contract on Host
---
> Refactor session and persist contract on Host

- go.mod
- go.sum
bug fix
- Use tron-us go-ipld-format to fix add panic on large files
---
> BTFS-1282 Use tron-us go-ipld-format to fix add panic on large files

- core/commands/rm.go
files
bugfix + refactor
- Refactor `btfs rm` and fix recursive removal of reed solomon files
---
> BTFS-1277: Refactor `btfs rm` and fix recursive removal of reed solomon

- core/commands/guard.go
- core/commands/storage.go
- core/commands/storage/contract.go
- core/commands/storage/contract_test.go
- core/commands/storage/session.go
- core/guard/challenge.go
- core/guard/contract.go
> BTFS-1252: Persist storage challenge object on renter and host

- core/commands/storage.go
- core/escrow/escrow.go
- go.mod
- go.sum
feature
renter submit contract to escrow, ledger will return error if renter doesn't have enough balance in ledger account
renter will query account balance from escrow before submit contract, if not enough balance to pay the contract total price, just abort before submit contract to escrow
no
add …
> Add balance check before submit contract to escrow

- core/commands/storage.go
- core/guard/contract.go
- go.mod
- go.sum
> repair flow

- core/commands/metadata.go
- core/commands/root.go
- core/commands/storage.go
This PR introduces help text updates for the btfs storage and btfs metadata commands in the CLI. 
No change in functional behavior
No change in functional behavior
No
N/A
I have updated the help text for btfs storage and btfs metadata commands. Help text that had spelling or grammatical errors were …
> [BTFS-971]New BTFS Storage & Metadata help text polish

- core/commands/rm.go
bugfix
btfs rm works on unpinned files
btfs rm returns output correctly to command line
---
> Btfs rm fix

- core/commands/storage.go
- core/commands/storage/challenge.go
- core/commands/storage/challenge_test.go
- core/commands/storage/session.go
- core/coreapi/pin.go
- go.mod
- go.sum
feature
host stored files now have the correct expired time set on pins
---
> BTFS-1355: Add pin expiration when host stores shard/file

- core/node/groups.go
- go.mod
- go.sum
> BTFS-1366: Read priv key from BTFS_PRIV_KEY for override

- core/commands/storage.go
- go.mod
- go.sum
> Some clean up and use testnet mode on dev profile

- Dockerfile.dev
- Dockerfile.prod
- bin/container_daemon_dev
- bin/container_daemon_prod
> Dockerfile 4 dev prod

- core/commands/config.go
- core/guard/contract.go
> optin to default storage host feature

- bin/container_daemon
> Bump up repair storage size (peak temporary storage)

- bin/container_daemon
> Make config consistent on repair node restart

- cmd/btfs/daemon.go
- core/commands/config.go
- go.mod
- go.sum
> V1 migrations

- go.mod
- go.sum
- version.go
> Use version 1.0.0 and update config migrations

- core/commands/storage.go
> Host Session Control Refactor

- core/guard/conn.go
- go.mod
> set timeout for guard client

- go.mod
- go.sum
- repo/fsrepo/fsrepo.go
feature
testnet is using the same swarm key as mainnet
testnet is isolated
- Add testnet swarm key (switchable)
- Use default swarm key inside config
- Add testnet-specific profiles
---
* **Please make sure the following procedures have been …
> Use set swarm key from config

- core/commands/storage.go
- core/commands/storage/session.go
- go.sum
bugfix
hosts cannot store shards correctly
guard contract is passed down directly and host can store shards
---
> BTFS-1417: Fix host shard download

- core/commands/cmdenv/env.go
- core/commands/rm.go
- pin/pin.go
> BTFS-1408: Use offline api when checking for rm blocks

- core/commands/storage/session.go
- Add a check on shard index so out of order arrivals of guard contracts can be saved in place (for hosts)
---
> BTFS-1452: Fix panic when saving guard contract on host

- core/commands/storage.go
> fix bug of upload status

- core/commands/storage.go
Fix logic error on local test mode enabled by default.
local test mode enabled by default.
local test mode enabled only on the option specified to true.
no
---
* **Please make sure the following procedures have been applied before requesting …
> switch off local test mode enabled by default

- core/commands/storage.go
> set RunTimeout to 15m

- core/commands/storage.go
- core/corehttp/remote/peer.go
> BTFS-1491 add /p2p-circuit/btfs/ address

- core/corehttp/webui.go
WebUI Update
WebUI uses v0 APIs
WebUI uses v1 APIs
No
None
WebUI with v1 APIs is being updated with a new hash. 
---
> [BTFS-1444]Update WebUI Hash 

- core/commands/storage.go
- core/hub/sync.go
> BTFS-1488: btfs hosts storage info should display default config mode by

- go.mod
- go.sum
> BTFS-1529: enable auto relay

- core/commands/storage.go
> BTFS-1532: handle err

- core/commands/storage.go
- core/commands/storage/session.go
> BTFS-1493-2

- cmd/btfs/init.go
- go.mod
- go.sum
> BTFS-1540: Clear out the Addresses.Announce to blank and disable

- core/corehttp/webui.go
Some updates from Alvin and Uchenna.
WebUI updates again
Browser does not say BTFS in favicon. Also, Settings is "Title" in english. 
Naming issues updated. 
No
None
See above
---
* **Please make sure the following procedures have been applied …
> Update WebUI Hash Again

- core/commands/storage.go
- core/escrow/escrow.go
- go.mod
- go.sum
> support customized payout period

- core/commands/storage/session.go
> rm some unnecessary lock

- bin/container_daemon
> update the services config url for repairer node

- bin/container_daemon
> fix repaire node error

- core/commands/storage.go
- version.go
> Next dev version

- core/commands/storage.go
- core/commands/storage/session.go
- core/corehttp/remote/peer.go
> BTFS-1570: Check session end status before retrying more goroutines

- core/coreunix/test/metadata_test.go
> BTFS-1578-2

- version.go
> bump dev version

- core/commands/storage.go
> extend timeout for checkPaymentFromClient

- core/commands/storage.go
> Fix shard timeout not ending when session ended.

- core/commands/get.go
- pin/pin.go
Also fix a bug on pin check api not skipping bad pins.
---
> BTFS-1369: Add quiet mode to btfs get repair shards

- core/coreapi/unixfs.go
- go.mod
- go.sum
> BTFS-1582-2

- core/commands/storage.go
- go.sum
> Merge 1.0.2 release fixes to master

- core/commands/storage.go
- core/commands/storage/session.go
> optimize retry limit

- core/commands/get.go
- core/commands/storage/session.go
> BTFS-1522 

- core/commands/storage.go
- core/commands/storage/context.go
impossible from renter -> host due to various reasons (network,
canceled, buggy challenge prep etc.)
---
> BTFS-1627: Fix potential host mem leak when downloading shard is

- core/commands/storage.go
contract with inquiring renter
---
> BTFS-1587: Check storage host has enough space before initiating

- core/commands/storage.go
- go.mod
- go.sum
> BTFS-1479: Static api config & arg validation

- core/commands/storage.go
> BTFS-1200: Add disable-host-mode in host announce command

- core/commands/storage.go
> skip host when StoragePriceAsk > price

- core/commands/guard.go
- core/commands/storage.go
- core/commands/storage/reed_solomon.go
- core/commands/storage/reed_solomon_test.go
- core/commands/storage/session.go
- core/guard/contract.go
> BTFS-1604: change FileSize to real file size from 10000 when submit file_meta to guard

- version.go
> 1.0.4-dev version bump

- core/commands/storage.go
Made the following updates:
1. Updated BTT to JUST, updated price values as well
2. Updated host storage announce price and bandwidth to Min, instead of Max.
CLI help docs
No
N/A
Updated CLI help docs
---
* **Please make sure the following …
> [BTFS-1671]Update help commands

- README.md
Updated Readme documentation section on how to build from source in MacOS, Linux VM, and docker. 
N/A
No change. 
No
N/A
See above.
---
> [BTFS-1673]Build from source readme

- core/commands/storage/hosts.go
- spin/analytics.go
> Btfs 1717: fix send storage config to status-server

- core/commands/storage.go
- core/commands/storage/hosts.go
- core/commands/storage/hosts_test.go
- core/hub/settings.go
- core/hub/settings_test.go
- spin/analytics.go
- spin/hosts.go
> BTFS-1674: Follow up to fix host announce not storing storage config

- version.go
> Update version.go to 1.1.0-dev

- core/commands/store/hosts/hosts.go
> BTFS-1670: Optimize local hosts swarm connect in the background

- core/commands/store/contracts/contracts.go
- core/commands/store/stats/stats.go
- core/commands/store/upload/helper/hosts.go
- core/commands/store/upload/upload.go
> backend api update for host ui

- core/commands/store/challenge/challenge.go
- core/commands/store/upload/upload.go
> SolveChallenge

- core/commands/store/upload/ds/sessions.go
- core/commands/store/upload/ds/shards.go
- core/commands/store/upload/upload.go
> BTFS-1755/BTFS-1773

- cmd/btfs/daemon.go
- core/commands/store/stats/stats.go
- go.mod
- go.sum
- spin/hosts.go
> BTFS-1788: Return storage disk total in btfs storage stats

- core/commands/store/stats/stats.go
- go.mod
- go.sum
> BTFS-1788: Add storage disk available to StorageStat

- core/commands/store/contracts/contracts.go
- core/escrow/escrow.go
- core/guard/conn.go
- core/guard/contract.go
> BTFS-1820: Use batch api for getting payout status on contracts

- core/commands/store/announce/announce.go
- core/commands/store/info/info.go
- core/commands/store/stats/stats.go
- go.mod
- go.sum
> BTFS-1848: Allow apis to work even when host mode is offline

- core/commands/store/upload/init.go
> BTFS-1632: Add backoff retry when downloading shards on host

- core/commands/store/stats/stats.go
only the locally available disk stats without querying/returning
the network stats.
---
> Add an option local-only to storage stats info to return

- version.go
> bump 1.1.1-dev

- go.mod
- go.sum
- install_btfs.sh
> Btfs 1885 Update go-btfs-config to v0.5.1 and remove api http header config

- version.go
> v1.1.2-dev

- core/commands/storage/upload/guard/guard.go
- core/commands/storage/upload/upload/do_guard.go
- core/commands/storage/upload/upload/do_pay.go
- core/commands/storage/upload/upload/do_sign_balance.go
- core/commands/storage/upload/upload/do_sign_channel_commit.go
- core/commands/storage/upload/upload/do_sign_guard_contracts.go
- core/commands/storage/upload/upload/do_waitupload.go
- core/commands/storage/upload/upload/upload_shard.go
> fix error event typo

- core/commands/storage/upload/upload/init.go
- core/commands/storage/upload/upload/upload.go
> BTFS-1894:check length of req.Arguments

- core/commands/storage/upload/helper/hosts_helper.go
- core/commands/storage/upload/sessions/renter_sessions.go
- core/commands/storage/upload/upload/init.go
- core/commands/storage/upload/upload/upload.go
- core/commands/storage/upload/upload/upload_shard.go
> Refine swarm connect

- go.mod
- go.sum
> Update bootstrap nodes from config

- core/commands/storage/upload/helper/hosts_helper.go
> BTFS-1897: fix not enough hosts

- core/commands/storage/upload/guard/guard.go
- core/commands/storage/upload/helper/hosts_helper.go
- core/commands/storage/upload/sessions/renter_sessions.go
- core/commands/storage/upload/upload/do_guard.go
- core/commands/storage/upload/upload/do_pay.go
- core/commands/storage/upload/upload/do_sign_balance.go
- core/commands/storage/upload/upload/do_sign_channel_commit.go
- core/commands/storage/upload/upload/do_sign_guard_contracts.go
- core/commands/storage/upload/upload/do_waitupload.go
- core/commands/storage/upload/upload/init.go
- core/commands/storage/upload/upload/upload.go
- core/commands/storage/upload/upload/upload_shard.go
- go.mod
- go.sum
- version.go
> v1.1.2 release

- core/commands/rm/rm.go
- core/commands/storage/contracts.go
- core/commands/storage/upload/sessions/host_shards.go
Also since release has already stored the wrong contracts for some,
add additional filter for protection.
---
> BTFS-1903: Fix host contracts are stored under wrong prefix

- core/commands/storage/upload/helper/hosts_helper.go
- core/commands/storage/upload/upload/do_guard.go
- core/commands/storage/upload/upload/do_waitupload.go
- core/commands/storage/upload/upload/init.go
> swarm connect to renter and challenge node

- core/commands/storage/hosts.go
- core/commands/storage/upload/sessions/renter_sessions.go
- core/commands/storage/upload/upload/upload_shard.go
- spin/hosts.go
As local command may get stuck or lose context after terminating command.
---
> BTFS-1905: Only sort swarm hosts on the daemon

- core/commands/storage/upload/sessions/renter_sessions.go
- core/commands/storage/upload/upload/upload_shard.go
> BTFS-1905: Better error message printing and less verbose info

- core/commands/rm/rm.go
- core/commands/storage/contracts.go
- core/commands/storage/hosts.go
- core/commands/storage/upload/helper/hosts_helper.go
- core/commands/storage/upload/sessions/host_shards.go
- core/commands/storage/upload/sessions/renter_sessions.go
- core/commands/storage/upload/upload/do_guard.go
- core/commands/storage/upload/upload/do_waitupload.go
- core/commands/storage/upload/upload/init.go
- core/commands/storage/upload/upload/upload_shard.go
- spin/hosts.go
> v1.1.2 fixes

- version.go
> Bump v1.2.0-dev

- test_pkgs.txt
bug fix to run unit tests in the test subdir for core/coreapi and core/coreunix
no tests are run under the packages' test dir
run the tests inside the test dir
no
no
---
* **Please make sure the following procedures have been applied before …
> BTFS-582 also run tests under test subfolder

- core/commands/storage/upload/upload/init.go
- core/commands/storage/upload/upload/upload_shard.go
> BTFS-1907: Host should verify amount in contract before signing

- cmd/btfs/generatekey_test.go
- cmd/btfs/init.go
- core/commands/commands_test.go
- core/commands/config.go
- core/commands/storage/wallet.go
- core/commands/wallet.go
- go.mod
- go.sum
> BTFS-1968 BTFS-1969 BTFS-1971

- core/commands/storage/upload/upload/upload_shard.go
> BTFS-1996 Prod storage upload may end with host timeout before trying out all the hosts

- cmd/btfs/init.go
- core/commands/config.go
> fix empty mnomenic issue

- core/commands/wallet.go
- core/wallet/wallet.go
> fix balance issues

- core/commands/wallet.go
- core/wallet/wallet.go
> hotfix for balance issues

- cmd/btfs/init.go
> [BTFS-2040]fix import key issues

- cmd/btfs/main.go
> Revert "BTFS-2022"

- version.go
> v1.3.0-dev version bump

- core/commands/commands_test.go
- core/commands/wallet.go
- version.go
> v1.2.1 release

- create_githubrelease.sh
A standalone script to create GitHub release and upload assets
N/A
N/A
No
No
A standalone script to create GitHub release and upload assets
---
> BTFS-2080 Create a GitHub release and upload assets

- go.mod
- go.sum
> fix crash when import invalid privateKey.

- core/commands/id.go
- go.mod
- go.sum
> BTFS-2114: Fix upload test issues

- core/wallet/tron.go
- core/wallet/tron_test.go
> BTFS-2082: use solidity domain

- spin/analytics.go
> BTFS-1904: remove health alert and error sending code in go-btfs spin/analytics

- core/commands/storage/upload/helper/hosts_helper.go
- version.go
> Bump 1.3.1-dev

- core/commands/storage/upload/helper/hosts_helper.go
- core/commands/storage/upload/helper/upload_helper.go
- core/commands/storage/upload/upload/do_guard.go
- core/commands/storage/upload/upload/do_waitupload.go
- version.go
> v1.3.1 release

- core/commands/storage/upload/helper/upload_helper.go
- core/commands/storage/upload/upload/do_guard.go
- core/commands/storage/upload/upload/do_waitupload.go
> Release 2 master

- version.go
> v1.3.2-dev

- core/commands/storage/path.go
…FS_PATH is set.`
BTFS-2210: fix `Host folder always creates another /.btfs after path.`
---
> BTFS-2210 & BTFS-2211

- core/corehttp/hostname.go
> Add gateway dev/staging and soter subdomain redirects

- core/commands/storage/path.go
> fix path issue

- core/commands/storage/path.go
> ignore .btfs.properties when BTFS_PATH env is not empty

- core/commands/storage/stats_cmd.go
> Bump stats info time due to slower disk access

- cmd/btfs/autoupdate.go
- core/commands/restart.go
- core/commands/storage/path.go
> fix path issues

- version.go
> bump v1.3.3-dev

- core/commands/config.go
- core/commands/storage/path.go
> BTFS-2175: remove remote protect from config and path commands

- core/corehttp/hostname.go
> Remove btfs.io from gateway domain list to use specific fqdn

- core/commands/storage/files/list.go
- core/commands/storage/upload/sessions/datastore.go
- core/commands/storage/upload/upload/init.go
> Renew Fixing

- core/commands/storage/challenge/challenge.go
> Increase challenge and response timeouts

- core/commands/commands_test.go
- core/commands/storage/path.go
- core/hub/settings_test.go
> BTFS-2254: fix set path issue

- core/commands/id.go
- go.mod
- go.sum
> BTFS-2220: add tron address

- core/commands/commands_test.go
- core/commands/storage/path.go
> fix set path issue

- core/commands/storage/hosts.go
- spin/hosts.go
> Remove preemptive hosts sort on sync

- core/commands/commands_test.go
- core/commands/config.go
- core/commands/id.go
- core/commands/storage/challenge/challenge.go
- core/commands/storage/hosts.go
- core/commands/storage/path.go
- core/commands/storage/store.go
- core/commands/storage/upload/upload/contracts.go
- core/commands/storage/upload/upload/do_waitupload.go
- core/commands/storage/upload/upload/host_manager.go
- core/commands/storage/upload/upload/host_manager_test.go
- core/commands/storage/upload/upload/init.go
- core/corehttp/hostname.go
- core/hub/settings_test.go
- go.mod
- go.sum
- spin/contracts.go
- spin/hosts.go
- version.go
> v1.3.3 release

- version.go
> v1.3.4-dev bump

- core/wallet/transaction.go
> BTFS-2261: retry when close channel failed

- core/commands/commands_test.go
- core/commands/root.go
- core/commands/tron.go
- core/wallet/tron.go
- core/wallet/tron_test.go
- core/wallet/wallet.go
> BTFS-2173: add tron commands

- core/commands/commands_test.go
- core/commands/restart.go
- core/commands/root.go
- core/commands/tron.go
- core/wallet/transaction.go
- core/wallet/tron.go
- core/wallet/tron_test.go
- core/wallet/wallet.go
- version.go
> v1.3.4 release

- core/commands/storage/upload/sessions/datastore.go
- core/commands/storage/upload/sessions/renter_sessions.go
> fix mem issue

- spin/sessions.go
> Fix renter sessions check loop

- core/commands/storage/upload/upload/do_sign_escrow_contracts.go
- core/commands/storage/upload/upload/init.go
- go.mod
- go.sum
> BTFS-2283: Change on the first Challenge

- hostui/banner.xml
> change banner url

- core/wallet/signature.go
- go.sum
> Fix sig issue

- go.sum
> Update banner url with bin gen

- core/commands/storage/upload/upload/status.go
- go.sum
> BTFS-2275:`btfs storage upload status` should return latest status

- core/commands/storage/upload/upload/do_sign_balance.go
- core/commands/storage/upload/upload/do_waitupload.go
- core/wallet/wallet.go
- go.mod
- go.sum
> refactor: extract ledger.NewSignedCreateAccountRequest function.

- core/wallet/speed_windows.go
> fix windows build

- go.mod
- go.sum
https://github.com/TRON-US/go-btfs-config/releases/tag/v0.6.10
---
> bump config version

- core/commands/storage/announce.go
- core/commands/storage/helper/hosts.go
- core/hub/settings.go
- core/hub/settings_test.go
- spin/analytics.go
- spin/hosts.go
> BTFS-2087: Support switching customized pricing and getting network

- core/commands/wallet.go
- go.mod
- go.sum
> fix non local cmds issue

- core/wallet/wallet.go
> fix: stuck on deposit when the account is new.

- core/commands/storage/upload/sessions/renter_shards.go
- core/commands/storage/upload/upload/contracts.go
- go.mod
- go.sum
> BTFS-2279 BTFS-2327: Support paged payout status queries

- sync_binaries.sh
> Fix a typo in the Shell script shebang

- core/commands/storage/upload/upload/init.go
- go.mod
- go.sum
> BTFS-2284: Make common failure logs less verbose on host

- core/commands/rm/rm.go
- core/commands/storage/announce.go
- core/commands/storage/info.go
- core/commands/storage/upload/sessions/renter_shards.go
- core/commands/storage/upload/upload/contracts.go
> Fix sync contracts

- core/commands/storage/info.go
- core/commands/storage/upload/helper/hosts_helper.go
BTFS-2087: Support switching customized pricing and getting network
---
> BTFS_2195: Use swarm connected hosts as backup hosts when uploading

- core/commands/storage/upload/upload/do_sign_escrow_contracts.go
- core/commands/storage/upload/upload/upload_shard.go
- go.mod
- go.sum
> BTFS-2368: Fix NumPayouts value in go-btfs

- .github/workflows/ci.yml
* Testing github action
Signed-off-by: thatInfrastructureGuy <thatInfrastructureGuy@gmail.com>
* Update ci.yml
* Add more actions
Signed-off-by: thatInfrastructureGuy <thatInfrastructureGuy@gmail.com>
* Add master tag
Signed-off-by: thatInfrastructureGuy <thatInfrastructureGuy@gmail.com>
* Updated secret name in master
* Update master.yml
* Create release-branch.yml
* Update master.yml
* Update master.yml
* Update master.yml
* Delete release-branch.yml
* Delete release-tags.yml
* Update Dockerfile
* Update master.yml
* Update master.yml
* Update master.yml
* Update master.yml
* Delete master.yml
* Create ci.yml
* Update ci.yml
* Update Dockerfile
* Update ci.yml
* Update ci.yml
* Update ci.yml
* Update ci.yml
> Add Github Actions to release branch

- .github/workflows/push.yml
> This PR attempts to remove redundant step and improve build time.

- chain/chain.go
- chain/config/config.go
- cmd/btfs/daemon.go
- settlement/swap/chequebook/cheque.go
- settlement/swap/swap.go
move 2 paras: initialDeposit && deploymentGas to chainconfig
> parameterized initialDeposit && deploymentGas

- chain/abi/abi.go
- chain/config/config.go
- core/commands/cheque/cheque.go
- settlement/swap/chequebook/chequebook.go
- settlement/swap/chequebook/factory.go
1 update backend api call to match contract
2 add new command for contract
> add cli & match new contract

- cmd/btfs/daemon.go
upgrade the generation function of private key and singer
> fix private key

- chain/abi/abi.go
- chain/config/config.go
> fix factory

- contracts/PriceOracle.sol
- contracts/SimpleSwap.sol
- contracts/SimpleSwapFactory.sol
> related contracts

- settlement/swap/chequebook/init.go
> print the important msg

- settlement/swap/chequebook/cashout.go
- settlement/swap/chequebook/chequebook.go
- settlement/swap/chequebook/factory.go
- settlement/swap/chequebook/init.go
- settlement/swap/erc20/erc20.go
send tx use 0 gas value, the send function will prepare the transaction
> send tx use default gas value

- .gitignore
- core/commands/storage/upload/helper/upload_helper.go
- core/commands/storage/upload/upload/upload.go
- core/commands/swarm.go
1.upload filehash, when btfs add it
2.add copy param to do upload
> upload filehash, when btfs add it
