TRON-US/go-btfs

.dockerignore
Dockerfile

Newer git submodule uses "absorbgitdirs" option by default which does not include .git folder inside a submodule.
Use a build time variable $gitdir to specify the location of the actual .git folder.

docker: fix build when running under a submodule folder

---

LICENSE-APACHE

This license file is not used in BTFS. BTFS is in MIT license.

Delete the LICENSE-APACHE file

---

core/commands/keystore.go

add ecdsa to the list of types allowed

[BTFSINFRA-370] fix key gen type

---

Dockerfile.testing

to use this dockerfile for running unit tests:
- create container from dockerfile: 
$ docker build -f Dockerfile.testing -t "btfs:make_test" .  (dont forget the dot there)
- start container to run unit test:
$ docker run -it <container number> 
- run bash in the container to look around:
$ docker run -it <container number> /bin/bash

BTFSINFRA-390 new Dockerfile.testing for unit testing container

---

cmd/btfs/init.go

**PR**:
This PR introduces changes to the validation of the seed phrase.
**Check 1:**
In order to accomplish TronLink compatibility, the seed phrase requires 128bit entropy, which translates into 12 words. The first check is therefore ensuring proper seed phrase length.
**Check 2:**
The words in the seed phrase need to come from BIP39 english dictionary. This check accomplishes that.
**Error messages:**
Check 1 returns an error indicating wrong number of words in the seed phrase. Assuming there were 11 words in the seed phrase, the corresponding error message would be "The seed phrase required to generate TRON private key needs to contain 12 words. Provided mnemonic has 11 words."
Check 2 returns an error indicating the invalidity of the seed phrase. Assuming that the following seed …

Added seed phrase checking.

---

analytics/analytics.go
cmd/btfs/init.go
core/commands/config.go
core/commands/pin.go

**This PR introduces a feature to opt-in and opt-out of analytic data collection.**
Submitted changes include:
**config.go**
Config command is modified, and introduces two new subcommands: optin, and optout.
**Optin** modifies the in-memory stored configuration (within repo object), and is used for life change. In addition, the file system repo is changed (config file is updated), making the change persistent. Upon successive launch of the deamon, the state of the configuration variable Experimental. Analytics is the same as before daemon terminated.
**Optout** performs operation opposite to optin. It disables collection and storing of analytic information.
**pin.go**
Introduces the usage of RemoveOnUnpin configuration variable.
**init.go**
Sets the RemoveOnUnpin variable to false by …

Implemented optin and optout commands as subcommand of config.

---

cmd/btfs/daemon.go

added enable-startup-test as the flag to turn on/off start up test. default to true
usage : 
btfs daemon --enable-startup-test=0
tested end to end

[BTFSINFRA-522] Funtest flag

---

core/commands/storage.go
core/hub/sync.go

* If --hosts is not defined, use the default stored hosts from btfs-hub
* Add auto/manual mode of using chunk hashes
* Add a flag to support both modes “Add auto/manual mode of using chunk hashes”
* point hub from fixed ip to dev domain

[BTFSBTT-252] and [BTTFSBTT-177]

---

sync_binaries.sh

download signed binaries and config yaml files from distributions.btfs.io and put them in github btfs-binary-releases.  
this script is run by the new jenkins job and can also be run locally if needed.

BTFSINFRA-576 new script to download signed binaries and files

---

core/commands/block.go
core/commands/cat.go
core/commands/files.go
core/commands/get.go
core/commands/object/object.go
core/commands/storage.go
core/coreapi/block.go
core/coreapi/object.go
core/coreapi/unixfs.go
core/corehttp/gateway_handler.go
core/corehttp/gateway_test.go
core/coreunix/add.go
fuse/readonly/ipfs_test.go
go.mod
go.sum
test/integration/addcat_test.go
test/integration/bench_cat_test.go
test/integration/three_legged_cat_test.go

1. core/commands/* has command driver changes for "btfs get" and "btfs cat" and minor changes in other files.
2. core/coreapi/object.go has changes for new metadata structure and 
token metadata retrieval functions. 
3. core/coreapi/unixfs.go has changes for drivers for DAG building (which is verified from
go-unixfs/balanced/balanced_test.go and go-unixfs/io/read_solomon_dagreader_test.go with 
go-unixfs/test/utils.go:GetNode()) and a method to attach metadata.

BTFS-684: go-btfs changes. Also includes changes for BTFS-721

---

docker-compose.yml

here is the PR to merge to release branch.  jenkins will run docker-compose to build binaries to eliminate variability in the version of go.

BTFS-937-release add docker-compose to build binaries

---

docker-compose.yml

pr based on the correct parent branch this time.  thanks.

BTFS-937 use same dockerfile image to build binaries

---

core/coreapi/object.go
core/coreunix/add.go
core/coreunix/metadata.go
core/coreunix/test/add_test.go
core/coreunix/test/metadata_test.go
go.mod
go.sum

- During adding of a reed solomon chunked file, read the metadata bytes from the chunker and insert directly into the tokenmetadata field
- Moved metadata helpers from coreapi/ into coreunix/ for coreunix functions to use them - also fixed the issue of unmarshalling raw dag node - now it unmarshals the fs node data correctly
- Moved coreunix tests into coreunix/test to avoid circular dependencies

BTFS-648: Add metadata into reed solomon chunker

---

.github/example_pull_request.md

Docs update.
There is only the pull request template, but no clear example of how to actually use iit.
The pull request template has an example under .github/example_pull_request.md.
BTFS-734 is also happy about this change.
No. Users can continue using their BTFS nodes without …

BTFS-734: Create example_pull_request.md

---

core/commands/storage.go
core/coreunix/metadata.go
core/hub/sync.go
go.mod
go.sum
spin/analytics.go
spin/hosts.go

New feature / change: now `btfs storage upload <file-hash>` must be a reed solomon encoded file
Storage upload flow can take any file / chunks to upload to hosts
Storage upload flow must use reed solomon encoded file - must pass validation
N/A (unreleased command)
* **What …

BTFS-713: Storage upload command uses reed solomon encoded file

---

core/commands/storage.go
core/commands/storage/challenge.go
core/commands/storage/challenge_test.go

Feature: send challenge questions from renter to guard
Challenge was using old chunk hash + nonce generation method
Challenge now generates chunk index + nonce and updates existing code and tests
Yes - but no one is using the /storage/upload apis yet
- Use chunk index instead of chunk id for DAG …

BTFS-1004: Prep guard challenges (part 1)

---

cmd/btfs/daemon.go

* **What kind of change does this PR introduce?** 
Bug fix
--dc flag overwrites config(analytics=false) if not given
--dc flag only overwrites config(analytics) if specified
https://tronnetwork.atlassian.net/browse/BTFS-1121
no
no
---

[BTFS-1121] fix: missing --dc flag overwrite config issue

---

cmd/btfs/daemon.go
core/corehttp/commands.go
core/corehttp/option_test.go
go.mod
go.sum
spin/analytics.go
version.go

Bugfixes from v0.2.3 release
Status server send does not work properly
Send analytics works with latest status server
No
- Same changes (merged with master changes) from https://github.com/TRON-US/go-btfs/pull/258
- Update version from now on to 1.0.0-dev (so to be different from 0.2.x)
---
* …

Fixes from v0.2.3 -> master

---

core/corehttp/webui.go
version.go

This PR updates go-btfs version and also the new hash value of the WebUI build folder. 
Old go-btfs version as well as old WebUI build folder hash. 
New go-btfs version and new WebUI build folder hash. 
Not sure if it's a breaking change, but updating go-btfs version will trigger autoupdate later. 
None
* **Description of …

[BTFS-1155]Updating the latest WebUI Hash

---

go.mod
go.sum

btfs add
Bug fix
`btfs add --chunker=reed-solomon` hangs for large files in offline mode
The above bug is fixed
https://github.com/TRON-US/go-btfs-chunker/pull/8
https://github.com/TRON-US/go-unixfs/pull/19
- Add a read check at the end of the stream of reed solomon chunker so that it always …

Update go-btfs-chunker to fix reed solomon chunker issue during offline

---

core/coreunix/add.go
core/coreunix/test/metadata_test.go
go.mod
go.sum

BTFS-1141: Reed Solomon based operations on 2-level directory object with metadata should work.
"btfs add -m $metadata-string $directory" on directory does not attach metadata under the given directory.
"btfs add -m $metadata-string $directory" attach metadata as child under the given directory.
N/A …

BTFS-1141: Reed Solomon based operations w/ per file replication unit

---

core/commands/storage.go
go.mod
spin/hosts.go

feature
get from remote when storage announce first time
---

feat: get from remote when storage announce first time

---

autoupdate/main.go
cmd/btfs/autoupdate.go
cmd/btfs/daemon.go

Auto updater process now passes hval to the newly updated process.
Refactor auto updater process a bit to remove bloat.
Bugfix: hval is preserved after auto update
---
* **Please make sure the following procedures have been applied before …

BTFS-1207: Pass hval to auto updating process and refactor

---

sync_binaries.sh

bug fix
https://tronnetwork.atlassian.net/browse/BTFS-1249
we dont need to pull down the config yaml anymore since the tarball/zip has it already
no
no
edit script file to not perform a wget of the config yaml files

BTFS-1249 remove wget of config yaml file since in tarball now

---

cmd/btfs/autoupdate.go

Tested autoupdate on darwin and windows using dist.btfs.io with and without the yaml in the compressed binary tarball/zip.
bugfix
autoupdate errors out when autoupdate to tar.gz or .zip contains config.yaml
autoupdate will delete the config.yaml, then uncompress/untar and then check again to see if config.yaml is there.  if not it will download the config.yaml again.
no
* **What dependencies / modules need to be updated as …

BTFS-1275 handle case where compressed file may contain config.yaml

---

core/commands/storage.go
core/commands/storage/hosts.go
core/commands/storage/hosts_test.go
core/hub/sync.go
go.mod
go.sum

Support modes from new hub proto definitions, notably, the testnet mode to download test-specific nodes information to datastore.
---

BTFS-1320: Support more hub sync and upload modes

---

core/commands/pin.go
core/commands/rm.go
core/coreapi/pin.go
go.mod
go.sum

Feature
Host stored files can be unpinned and removed easily
Must use --force to pin rm host stored file (unexpired file)
---

BTFS-654: Do not allow btfs pin rm and btfs rm if file has not expired

---

README.md

2 changes:
1) Added the invite link to Discord community
2) Updated the correct link to Install BTFS docs.btfs.io page
Documentation
No Discord invite link and the BTFS Install docs link is 404 error
Added Discord invite link and valid BTFS Install docs link
No
N/A
Added Discord invite link and …

[BTFS-1398]Update Readme

---

Dockerfile.unit_testing

remove extraneous parts in dockerfile.unit_testing and add `make build` to the docker container run command.
does not run `make build`
BTFS-1016
None
none

BTFS-1016 clean up dockerfile.unit_testing and run make build

---

package.sh
sync_binaries.sh

bug fix
package script reports error on rm if the binary-releases repo is not cloned
ignore missing files with the -f flag for rm command
no
no dependencies

BTFS-1280 perform rm -f since files may not be present

---

cmd/btfs/daemon.go
cmd/btfs/init.go
core/node/builder.go
go.mod
go.sum

address for announce
feature/fix
can override swarm address with external port
https://github.com/TRON-US/go-btfs-config/pull/26
---

BTFS-1508: btfs daemon can use swarm-port option to override swarm

---

cmd/btfs/autoupdate.go

bug fix
autoupdate will show an error message. see BTFS-1447
the version strings in both config.yaml on disk and the newly downloaded config.yaml will be checked for a dash in the 3rd slice.  if there is a dash, the autoupdate will not run.  a message is shown when when a dash is found saying autoupdate will not run.
no
none 
* …

BTFS-1447 bug fix, dash in version will not try to autoupdate

---

core/corehttp/commands.go
go.mod
go.sum

feature
redirecting /api/latest and legacy /api/v0 to /api/v1
https://github.com/TRON-US/go-btfs-cmds/pull/10
---

BTFS-1441: Redirect /api/latest and /api/v0 to /api/v1

---

core/commands/rm.go

bugfix
btfs rm does not work for files (small) with identical data blocks
fixed
---

BTFS-1523: btfs rm should work for files with identical data blocks

---

cmd/btfs/autoupdate.go
sync_binaries.sh

the windows zip files will be named .zip instead of exe.zip
autoupdate expects go-btfs binaries for windows to be named exe.zip which is not conventional
the windows zip files will be named .zip instead of exe.zip
no.  we will still build and upload the exe.zip and plain zip files in the jenkins jobs.  eventually we will stop uploading the exe.zip files once everyone has upgraded post 1.0.2 beta 3.
* **What dependencies / modules …

BTFS-1536 fix autoupdate to not use .exe.zip file extensions anymore

---

Dockerfile
Dockerfile.testing
Dockerfile.unit_testing
README.md
go.mod
mk/golang.mk

To avoid the windows ddl preloading issue, upgrade docker go version to 1.14. Also change README and some reference place which defined go version.
Current docker go version is 1.13 which may cause ddl preloading issue. 
Jira ticket number BTFS-1850.
No
No
1. Change Dockerfiles from …

BTFS 1850 - Update Dockerfile golang version to 1.14

---

go.mod
go.sum
spin/analytics.go

BTFS-2308: bug: btfs node crashes with too many files / cpu info crash

---

core/commands/storage/path/path_unix.go

Fix build error where volumes() is undefined when building under FreeBSD.
The build error occurs on the below line without this patch: https://github.com/TRON-US/go-btfs/blob/5e9d9b1971f7e5b1d15999bf932e03e872151fa6/core/commands/storage/path/path.go#L302

Fix build error where volumes() is undefined when building under FreeBSD
